### ISSUE TITLE
Bug: The Spotify access token expire

### ISSUE THREAD

**Issue by MatitoDA** [SlimeCloud/java-SlimeBot#112]
**Describe the bug**
Access Token set in SpotifyListener:35 expire after a specific time

**To Reproduce**
1. Start bot
2. wait untill the token expired

**Solution idea**
[Here](https://stackoverflow.com/questions/30372835/how-can-i-increase-the-expiry-time-of-spotify-token) they wrote the token expire after 1h and you have to user a "refresh_token"
or maybe we set the access token every time we check the episodes/albums

**Additional context**
logs + error:
```log
21:09:29 JDA MainWS-ReadThread      JDA                  ERROR  One of the EventListeners had an uncaught exception
java.lang.ClassCastException: null
21:26:17 pool-1-thread-1            SpotifyListener      INFO   Überprüfe auf neue Podcast Folgen...
21:26:17 pool-1-thread-1            SpotifyListener      INFO   Überprüfe auf Einträge bei 0HNYFHg2WNq1P56qK6defn...
21:26:17 pool-1-thread-1            SpotifyListener      ERROR  Einträge können nicht geladen werden
se.michaelthelin.spotify.exceptions.detailed.UnauthorizedException: The access token expired
        at se.michaelthelin.spotify.SpotifyHttpManager.getResponseBody(SpotifyHttpManager.java:322)
        at se.michaelthelin.spotify.SpotifyHttpManager.get(SpotifyHttpManager.java:160)
        at se.michaelthelin.spotify.requests.AbstractRequest.getJson(AbstractRequest.java:110)
        at se.michaelthelin.spotify.requests.data.shows.GetShowsEpisodesRequest.execute(GetShowsEpisodesRequest.java:41)
        at se.michaelthelin.spotify.requests.data.shows.GetShowsEpisodesRequest.execute(GetShowsEpisodesRequest.java:17)
        at com.slimebot.alerts.spotify.SpotifyListener.getLatestEntries(SpotifyListener.java:88)
        at com.slimebot.alerts.spotify.SpotifyListener.lambda$check$1(SpotifyListener.java:58)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at com.slimebot.alerts.spotify.SpotifyListener.check(SpotifyListener.java:60)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
21:26:17 pool-1-thread-1            SpotifyListener      INFO   Überprüfe auf neue Musik Releases...
21:26:17 pool-1-thread-1            SpotifyListener      INFO   Überprüfe auf Einträge bei 0ZzsW7JiW4Ok3H7nFl4yV1...
21:26:17 pool-1-thread-1            SpotifyListener      ERROR  Einträge können nicht geladen werden
se.michaelthelin.spotify.exceptions.detailed.UnauthorizedException: The access token expired
        at se.michaelthelin.spotify.SpotifyHttpManager.getResponseBody(SpotifyHttpManager.java:322)
        at se.michaelthelin.spotify.SpotifyHttpManager.get(SpotifyHttpManager.java:160)
        at se.michaelthelin.spotify.requests.AbstractRequest.getJson(AbstractRequest.java:110)
        at se.michaelthelin.spotify.requests.data.artists.GetArtistsAlbumsRequest.execute(GetArtistsAlbumsRequest.java:41)
        at se.michaelthelin.spotify.requests.data.artists.GetArtistsAlbumsRequest.execute(GetArtistsAlbumsRequest.java:18)
        at com.slimebot.alerts.spotify.SpotifyListener.getLatestEntries(SpotifyListener.java:88)
        at com.slimebot.alerts.spotify.SpotifyListener.lambda$check$4(SpotifyListener.java:68)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at com.slimebot.alerts.spotify.SpotifyListener.check(SpotifyListener.java:70)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by MatitoDA** [comment]
#113
