### ISSUE TITLE
Multiple Choice Poll

### ISSUE THREAD

**Issue by cyklon73** [SlimeCloud/java-SlimeBot#146]
**ToDos**
- [ ] implement Multiple Choice Poll

**Description**
Implementation of multiple-choice surveys in which several options can be selected

**Comment by MatitoDev** [comment]
+ add a option to mention a role

**Comment by MineKing9534** [comment]
- fix long entries being to long for select menu

**Comment by MatitoDev** [comment]
```java
20:48:17 ForkJoinPool.commonPool-wo RestAction           ERROR  Encountered error while processing success consumer
java.lang.IllegalArgumentException: Label may not be longer than 100 characters! Provided: "#2  Kiste öffnet sich nur einmal für den spieler der sie geknackt hat und ist danach wieder verschlossen"
        at net.dv8tion.jda.internal.utils.Checks.check(Checks.java:69)
        at net.dv8tion.jda.internal.utils.Checks.notLonger(Checks.java:175)
        at net.dv8tion.jda.api.interactions.components.selections.SelectOption.<init>(SelectOption.java:94)
        at net.dv8tion.jda.api.interactions.components.selections.SelectOption.<init>(SelectOption.java:69)
        at net.dv8tion.jda.api.interactions.components.selections.StringSelectMenu$Builder.addOption(StringSelectMenu.java:206)
        at com.slimebot.commands.poll.PollCommand.lambda$performCommand$0(PollCommand.java:52)
        at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:121)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
        ```
